In [3]:
!pip install lightgbm

Requirement already satisfied: lightgbm in c:\users\jayas\anaconda3\lib\site-packages (4.6.0)
Requirement already satisfied: numpy>=1.17.0 in c:\users\jayas\anaconda3\lib\site-packages (from lightgbm) (2.1.3)
Requirement already satisfied: scipy in c:\users\jayas\anaconda3\lib\site-packages (from lightgbm) (1.15.3)

In [5]:
import pandas as pd # import library 
import numpy as np
import lightgbm as lgb

In [6]:
dataset= pd.read_csv("insurance.csv")  # function of pandas used to load the data
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [7]:
dataset=pd.get_dummies(dataset) #to create dummies value for categorical text
dataset

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,True,False,False,True
1,18,33.770,1,1725.55230,False,True,True,False
2,28,33.000,3,4449.46200,False,True,True,False
3,33,22.705,0,21984.47061,False,True,True,False
4,32,28.880,0,3866.85520,False,True,True,False
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,False,True,True,False
1334,18,31.920,0,2205.98080,True,False,True,False
1335,18,36.850,0,1629.83350,True,False,True,False
1336,21,25.800,0,2007.94500,True,False,True,False
1337,61,29.070,0,29141.36030,True,False,False,True

In [8]:
dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false
dataset

C:\Users\jayas\AppData\Local\Temp\ipykernel_7192\2063786219.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  dataset=dataset.replace({True:1,False:0}) #replce the 0 and 1 for true,false

,age,bmi,children,charges,sex_female,sex_male,smoker_no,smoker_yes
0,19,27.900,0,16884.92400,1,0,0,1
1,18,33.770,1,1725.55230,0,1,1,0
2,28,33.000,3,4449.46200,0,1,1,0
3,33,22.705,0,21984.47061,0,1,1,0
4,32,28.880,0,3866.85520,0,1,1,0
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,10600.54830,0,1,1,0
1334,18,31.920,0,2205.98080,1,0,1,0
1335,18,36.850,0,1629.83350,1,0,1,0
1336,21,25.800,0,2007.94500,1,0,1,0
1337,61,29.070,0,29141.36030,1,0,0,1

In [9]:
dataset = dataset.drop(columns=["sex_female", "smoker_no"])# drop columns from the dataset
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [10]:
independent=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]  # split input and output to get input from dataset 
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [11]:
dependent=dataset[['charges']] # get output from dataset
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [12]:
from sklearn.model_selection import train_test_split  # sklearn library for machine learning
x_train,x_test,y_train,y_test = train_test_split(independent, dependent,test_size=0.30,random_state=0)

In [147]:
from lightgbm import LGBMRegressor # import lightgbm  regressor for create model
regressor = LGBMRegressor(random_state=10, learning_rate=0.1)
regressor.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.000095 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 313
[LightGBM] [Info] Number of data points in the train set: 936, number of used features: 5
[LightGBM] [Info] Start training from score 13232.916456

LGBMRegressor(random_state=10)

In [148]:
y_pred=regressor.predict(x_test)

In [149]:
from sklearn.metrics import r2_score # measure the accuracy of the model
r_score=r2_score(y_test,y_pred)

In [150]:
r_score

0.86603193419773

In [151]:
import pickle   # store the model
filename = "finalized_model_LG_BOOST.sav" 
pickle.dump(regressor,open(filename,"wb"))

In [152]:
load_model=pickle.load(open("finalized_model_LG_BOOST.sav" ,"rb")) # load the model from the file
result=load_model.predict([[50,30.970,3,1,0]])

C:\Users\jayas\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [153]:
result

array([11693.28614141])